## Adapted from Libero sample configuration.
## https://github.com/libero/sample-configuration/blob/master/.travis.yml
sudo: required

language: minimal

services: docker

before_install:
  - docker -v
  # @todo change the name of env, add to ignore and add copy to init.
  # - cp .env.dist .env

install:
  - travis_retry docker-compose pull
  - docker build -t digirati/madoc-platform services/madoc
  - docker build -t digirati/madoc-platform-db services/madoc-database
  - docker build -t digirati/madoc-sorting-room services/sorting-room
  - docker build -t digirati/madoc-gateway services/gateway
  - docker build -t digirati/madoc-shared-postgres services/shared-postgres
  - docker build -t digirati/madoc-tasks-api services/tasks-api
  - docker build -t digirati/madoc-ts services/madoc-ts
  - docker build -t digirati/madoc-certs services/certs
  - docker build -t digirati/madoc-storage-api services/storage-api

  # v2 Beta tags
  - docker tag digirati/madoc-platform digirati/madoc-platform-beta
  - docker tag digirati/madoc-platform-db digirati/madoc-platform-beta-db
  - docker tag digirati/madoc-sorting-room digirati/madoc-sorting-room-beta
  - docker tag digirati/madoc-gateway digirati/madoc-gateway-beta
  - docker tag digirati/madoc-shared-postgres digirati/madoc-shared-postgres-beta
  - docker tag digirati/madoc-tasks-api digirati/madoc-tasks-api-beta
  - docker tag digirati/madoc-ts digirati/madoc-ts-beta
  - docker tag digirati/madoc-certs digirati/madoc-certs-beta
  - docker tag digirati/madoc-storage-api digirati/madoc-storage-api-beta

  # Add any database test fixtures to `database/sql` before madoc init-ci.
  - ./bin/madoc init-ci

before_script:
  - ./bin/madoc ci-start
  - ./.travis/wait-for-omeka.sh

script:
  - .travis/test-script.sh
# Travis build does not have PHP at this stage.
#  - .travis/check-translations.sh

after_script:
  - ./bin/madoc ci-stop

cache:
  bundler: true
  directories:
    - $HOME/docker

deploy:
  # Publishing v2 branch
  - provider: script
    script: bash ./.travis/docker-deploy.sh digirati/madoc-platform-beta
    on:
      branch: v2
  - provider: script
    script: bash ./.travis/docker-deploy.sh digirati/madoc-platform-beta-db
    on:
      branch: v2
  - provider: script
    script: bash ./.travis/docker-deploy.sh digirati/madoc-sorting-room-beta
    on:
      branch: v2
  - provider: script
    script: bash ./.travis/docker-deploy.sh digirati/madoc-gateway-beta
    on:
      branch: v2
  - provider: script
    script: bash ./.travis/docker-deploy.sh digirati/madoc-shared-postgres-beta
    on:
      branch: v2
  - provider: script
    script: bash ./.travis/docker-deploy.sh digirati/madoc-tasks-api-beta
    on:
      branch: v2
  - provider: script
    script: bash ./.travis/docker-deploy.sh digirati/madoc-ts-beta
    on:
      branch: v2
  - provider: script
    script: bash ./.travis/docker-deploy.sh digirati/madoc-certs-beta
    on:
      branch: v2
  - provider: script
    script: bash ./.travis/docker-deploy.sh digirati/madoc-storage-api-beta
    on:
      branch: v2

# Publishing master branch
  - provider: script
    script: bash ./.travis/docker-deploy.sh digirati/madoc-platform
    on:
      branch: master
  - provider: script
    script: bash ./.travis/docker-deploy.sh digirati/madoc-platform-db
    on:
      branch: master
# Publishing tags
  - provider: script
    script: bash ./.travis/docker-deploy.sh digirati/madoc-platform
    on:
      tags: true
  - provider: script
    script: bash ./.travis/docker-deploy.sh digirati/madoc-platform-db
    on:
      tags: true

if: |
  branch = master OR \
  branch = v2 OR \
  type = pull_request OR \
  tag IS present
