version: "3"
services:
  # Internal services

  gateway:
    ports:
      - "8988:8080"
    volumes:
      - ./e2e/test-fixtures/certs:/openssl-certs

  madoc:
    environment:
      - APP_ENV=TEST
    volumes:
      - ./var/test-environment/files:/srv/omeka/files
      - ./e2e/test-fixtures/certs:/openssl-certs

  certs:
    build:
      context: services/certs
    volumes:
      - ./e2e/test-fixtures/certs:/openssl-certs

  madoc-ts:
    build:
      context: services/madoc-ts
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=test
    volumes:
      - ./e2e/test-fixtures/certs:/openssl-certs
      - ./var/test-environment/jwt:/home/node/app/service-jwt-responses
      - ./var/test-environment/files:/home/node/app/omeka-files

  tasks-api: {}

  model-api: {}

  config-service: {}

  shared-postgres:
    volumes:
      - ./var/test-environment/shared-database:/var/lib/postgresql/data

  madoc-database:
    volumes:
      - ./e2e/test-fixtures/omeka/user.sql:/docker-entrypoint-initdb.d/99-user.sql
      - ./e2e/test-fixtures/omeka/site_permission.sql:/docker-entrypoint-initdb.d/99-site_permission.sql
      - ./e2e/utility/reset-database.sh:/opt/tools/reset-database.sh
      - ./var/test-environment/database/data:/var/lib/mysql/

  storage-api:
    volumes:
      - ./services/storage-api/lib:/home/node/app/lib:delegated
      - ./var/test-environment/files/storage-api:/home/node/app/files
