name: Madoc TS Docker (v2)

on:
  push:
    branches: [v2]
    paths:
      - ".github/workflows/madoc-ts-docker.yaml"
      - "services/madoc-ts/src/**"
      - "services/madoc-ts/migrations/**"
      - "services/madoc-ts/translations/**"
      - "services/madoc-ts/schemas/**"
      - "services/madoc-ts/themes/**"
      - "services/madoc-ts/package.json"
      - "services/madoc-ts/yarn.lock"
      - "services/madoc-ts/Dockerfile"
      - "services/madoc-ts/ecosystem.config.js"
      - "services/madoc-ts/webpack.config.js"
      - "services/madoc-ts/tsconfig.json"

jobs:

  madoc-ts-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push SHA to GitHub Packages
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: services/madoc-ts
          push: true
          tags: |
            ghcr.io/digirati-co-uk/madoc-ts:${{ github.sha }}
            ghcr.io/digirati-co-uk/madoc-ts:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
